version: "3"

services:
  loadbalancer:
    build: /loadbalancer
    image: loadbalancer:v1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - shard1
      - shard2
      - shard3
  
  shard1:
    build: /shard
    image: shard:v1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  shard2:
    build: /shard
    image: shard:v1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  shard3:
    build: /shard
    image: shard:v1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8003
    ports:
      - "8003:8003"